services:
  rabbitmq:
    build: .
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15670:15670
        - 15671:15671
        - 15672:15672
        - 15674:15674
        - 61613:61613
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge